contribution = {'E.coli':{1413:'C=C stretching in quinoid ring'},
'P.aeruginosa':{1088:'$v_1CO_3^{2-}$, $v_3PO_4^{3-}$, v(C-C) skeletal of acyl back-bone in lipid',
1125:'v(C-C) skeletal of acyl backbone in lipid',
1168:'v(C=C), δ(COH) of Lipids',
1413:'C=C stretching in quinoid ring'},
'C.joostei':{1130:'C-C stretching of carotenoid-like substance',
1445:'$δ(CH_2)$, $δ(CH_3)$, lipids',
1525:'C-C and conjugated C=C stretching of carotenoid',
1605:'C-C in-plane bending mode of phenylalanine and tyrosine'},
'E.faecalis':{1552:'v(C=C) of Tryptophan'},
'S.aureus':{1034:'Phenylalanine',
1210:'$C-C_6H_5$ stretching mode in tyrosine and phenylalanine',
1328:'NNucleic acids'},
'S.enterica':{968:'Lipids',
1413:'C=C stretching in quinoid ring',
1456:'CH2 bending of lipid'}}
